/*
 * Masters School — job positions seed (source of truth).
 * GENERATED BY tools/sync-jobs-seed.js — DO NOT EDIT BY HAND.
 */
'use strict';

var SEED_JOBS = [
  {
    "id": "german-teacher",
    "order": 0,
    "en": {
      "r": "German Teacher",
      "key": "German Teacher",
      "d": "Teaching",
      "ty": "Full-time",
      "desc": "Teach German to bilingual learners from Kindergarten to Secondary, building fluency and confidence step by step.",
      "resp": [
        "Plan and deliver engaging German lessons for different age groups",
        "Assess student progress and provide regular feedback",
        "Collaborate with colleagues to align the language curriculum",
        "Foster a love for the language and culture through classes and activities"
      ],
      "qual": [
        "Degree in German or a relevant education qualification",
        "Strong classroom management and communication skills",
        "Native or near-native German proficiency"
      ]
    },
    "ar": {
      "r": "معلم لغة ألمانية",
      "key": "معلم لغة ألمانية",
      "d": "التدريس",
      "ty": "دوام كامل",
      "desc": "تدريس اللغة الألمانية لطلاب ثنائيي اللغة من الروضة حتى الثانوية، مع بناء الطلاقة والثقة خطوة بخطوة.",
      "resp": [
        "إعداد دروس مشوّقة في الألمانية لمختلف الفئات العمرية",
        "تقييم تقدم الطلاب وتقديم تغذية راجعة منتظمة",
        "التعاون مع الزملاء في مواءمة مناهج اللغات",
        "تعزيز حب اللغة والثقافة من خلال الدروس والأنشطة"
      ],
      "qual": [
        "مؤهل في اللغة الألمانية أو مؤهل تربوي ذي صلة",
        "مهارات قوية في إدارة الصف والتواصل",
        "طلاقة أصلية أو شبه أصلية في الألمانية"
      ]
    }
  },
  {
    "id": "french-teacher",
    "order": 1,
    "en": {
      "r": "French Teacher",
      "key": "French Teacher",
      "d": "Teaching",
      "ty": "Full-time",
      "desc": "Teach French to bilingual learners from Kindergarten to Secondary, building fluency and confidence step by step.",
      "resp": [
        "Plan and deliver engaging French lessons for different age groups",
        "Assess student progress and provide regular feedback",
        "Collaborate with colleagues to align the language curriculum",
        "Foster a love for the language and culture through classes and activities"
      ],
      "qual": [
        "Degree in French or a relevant education qualification",
        "Strong classroom management and communication skills",
        "Native or near-native French proficiency"
      ]
    },
    "ar": {
      "r": "معلم لغة فرنسية",
      "key": "معلم لغة فرنسية",
      "d": "التدريس",
      "ty": "دوام كامل",
      "desc": "تدريس اللغة الفرنسية لطلاب ثنائيي اللغة من الروضة حتى الثانوية، مع بناء الطلاقة والثقة خطوة بخطوة.",
      "resp": [
        "إعداد دروس مشوّقة في الفرنسية لمختلف الفئات العمرية",
        "تقييم تقدم الطلاب وتقديم تغذية راجعة منتظمة",
        "التعاون مع الزملاء في مواءمة مناهج اللغات",
        "تعزيز حب اللغة والثقافة من خلال الدروس والأنشطة"
      ],
      "qual": [
        "مؤهل في اللغة الفرنسية أو مؤهل تربوي ذي صلة",
        "مهارات قوية في إدارة الصف والتواصل",
        "طلاقة أصلية أو شبه أصلية في الفرنسية"
      ]
    }
  },
  {
    "id": "arabic-teacher",
    "order": 2,
    "en": {
      "r": "Arabic Teacher",
      "key": "Arabic Teacher",
      "d": "Teaching",
      "ty": "Full-time",
      "desc": "Teach Arabic to bilingual learners from Kindergarten to Secondary, building fluency and confidence step by step.",
      "resp": [
        "Plan and deliver engaging Arabic lessons for different age groups",
        "Assess student progress and provide regular feedback",
        "Collaborate with colleagues to align the language curriculum",
        "Foster a love for the language and culture through classes and activities"
      ],
      "qual": [
        "Degree in Arabic or a relevant education qualification",
        "Strong classroom management and communication skills",
        "Native or near-native Arabic proficiency"
      ]
    },
    "ar": {
      "r": "معلم لغة عربية",
      "key": "معلم لغة عربية",
      "d": "التدريس",
      "ty": "دوام كامل",
      "desc": "تدريس اللغة العربية لطلاب ثنائيي اللغة من الروضة حتى الثانوية، مع بناء الطلاقة والثقة خطوة بخطوة.",
      "resp": [
        "إعداد دروس مشوّقة في العربية لمختلف الفئات العمرية",
        "تقييم تقدم الطلاب وتقديم تغذية راجعة منتظمة",
        "التعاون مع الزملاء في مواءمة مناهج اللغات",
        "تعزيز حب اللغة والثقافة من خلال الدروس والأنشطة"
      ],
      "qual": [
        "مؤهل في اللغة العربية أو مؤهل تربوي ذي صلة",
        "مهارات قوية في إدارة الصف والتواصل",
        "طلاقة أصلية أو شبه أصلية في العربية"
      ]
    }
  },
  {
    "id": "english-teacher",
    "order": 3,
    "en": {
      "r": "English Teacher",
      "key": "English Teacher",
      "d": "Teaching",
      "ty": "Full-time",
      "desc": "Teach English to bilingual learners from Kindergarten to Secondary, building fluency and confidence step by step.",
      "resp": [
        "Plan and deliver engaging English lessons for different age groups",
        "Assess student progress and provide regular feedback",
        "Collaborate with colleagues to align the language curriculum",
        "Foster a love for the language and culture through classes and activities"
      ],
      "qual": [
        "Degree in English or a relevant education qualification",
        "Strong classroom management and communication skills",
        "Native or near-native English proficiency"
      ]
    },
    "ar": {
      "r": "معلم لغة إنجليزية",
      "key": "معلم لغة إنجليزية",
      "d": "التدريس",
      "ty": "دوام كامل",
      "desc": "تدريس اللغة الإنجليزية لطلاب ثنائيي اللغة من الروضة حتى الثانوية، مع بناء الطلاقة والثقة خطوة بخطوة.",
      "resp": [
        "إعداد دروس مشوّقة للإنجليزية لمختلف الفئات العمرية",
        "تقييم تقدم الطلاب وتقديم تغذية راجعة منتظمة",
        "التعاون مع الزملاء في مواءمة مناهج اللغات",
        "تعزيز حب اللغة والثقافة من خلال الدروس والأنشطة"
      ],
      "qual": [
        "مؤهل في اللغة الإنجليزية أو مؤهل تربوي ذي صلة",
        "مهارات قوية في إدارة الصف والتواصل",
        "طلاقة أصلية أو شبه أصلية في الإنجليزية"
      ]
    }
  },
  {
    "id": "hr-specialist",
    "order": 4,
    "en": {
      "r": "HR Specialist",
      "key": "HR Specialist",
      "d": "Human Resources",
      "ty": "Full-time",
      "desc": "Run the recruitment cycle end to end and help keep Masters a positive, family-minded place to work.",
      "resp": [
        "Manage hiring, onboarding and staff records",
        "Support payroll inputs and HR policies",
        "Coordinate training and staff wellbeing initiatives"
      ],
      "qual": [
        "Degree in HR or business administration",
        "Experience with recruitment and Egyptian labour practices",
        "Discreet, organised and people-focused"
      ]
    },
    "ar": {
      "r": "أخصائي موارد بشرية",
      "key": "أخصائي موارد بشرية",
      "d": "الموارد البشرية",
      "ty": "دوام كامل",
      "desc": "إدارة دورة التوظيف من البداية إلى النهاية ودعم بيئة عمل إيجابية بروح العائلة في ماسترز.",
      "resp": [
        "إدارة التوظيف والتعيين وسجلات الموظفين",
        "دعم مدخلات الرواتب وسياسات الموارد البشرية",
        "تنسيق التدريب ومبادرات رفاهية الموظفين"
      ],
      "qual": [
        "مؤهل في الموارد البشرية أو إدارة الأعمال",
        "خبرة في التوظيف وقوانين العمل المصرية",
        "السرية والتنظيم والتركيز على الناس"
      ]
    }
  },
  {
    "id": "it-support",
    "order": 5,
    "en": {
      "r": "IT Support Engineer",
      "key": "IT Support",
      "d": "IT",
      "ty": "Full-time",
      "desc": "Keep classrooms, labs and offices running on reliable and secure technology every school day.",
      "resp": [
        "Maintain networks, devices and smart-classroom systems",
        "Resolve staff and student technical issues quickly",
        "Support the admissions and administration platforms"
      ],
      "qual": [
        "Degree or diploma in IT or computer science",
        "Hands-on experience with networks and user support",
        "Calm, methodical troubleshooting under time pressure"
      ]
    },
    "ar": {
      "r": "مهندس دعم تقني",
      "key": "دعم تقني",
      "d": "تكنولوجيا المعلومات",
      "ty": "دوام كامل",
      "desc": "إبقاء الفصول والمختبرات والمكاتب تعمل بتقنية موثوقة وآمنة طوال أيام الدراسة.",
      "resp": [
        "صيانة الشبكات والأجهزة وأنظمة الفصول الذكية",
        "حل مشكلات التقنية للموظفين والطلاب بسرعة",
        "دعم منصات القبول والإدارة"
      ],
      "qual": [
        "مؤهل في تقنية المعلومات أو علوم الحاسب",
        "خبرة عملية في الشبكات ودعم المستخدمين",
        "هدوء ودراسة منهجية للمشكلات تحت الضغط"
      ]
    }
  },
  {
    "id": "marketing-officer",
    "order": 6,
    "en": {
      "r": "Marketing Officer",
      "key": "Marketing Officer",
      "d": "Marketing",
      "ty": "Full-time",
      "desc": "Grow the Masters brand through campaigns, content and community outreach across El Santa and Gharbia.",
      "resp": [
        "Plan and run digital and offline campaigns",
        "Create engaging content and manage social media",
        "Organise open days and community events"
      ],
      "qual": [
        "Degree in marketing or communications",
        "Hands-on social media and content experience",
        "Creative, organised and fluent in English and Arabic"
      ]
    },
    "ar": {
      "r": "مسؤول تسويق",
      "key": "مسؤول تسويق",
      "d": "التسويق",
      "ty": "دوام كامل",
      "desc": "تنمية علامة ماسترز من خلال الحملات والمحتوى والتواصل المجتمعي في السنطة والغربية.",
      "resp": [
        "تخطيط وتنفيذ حملات رقمية وتقليدية",
        "إنشاء محتوى جذاب وإدارة وسائل التواصل",
        "تنظيم الأيام المفتوحة والفعاليات المجتمعية"
      ],
      "qual": [
        "مؤهل في التسويق أو الإعلام",
        "خبرة عملية في وسائل التواصل والمحتوى",
        "إبداع وتنظيم وإتقان الإنجليزية والعربية"
      ]
    }
  },
  {
    "id": "receptionist",
    "order": 7,
    "en": {
      "r": "Receptionist",
      "key": "Receptionist",
      "d": "Administration",
      "ty": "Full-time",
      "desc": "Be the warm first impression of Masters — greeting families and keeping the front office running smoothly.",
      "resp": [
        "Welcome visitors and answer calls professionally",
        "Handle parent enquiries and appointment scheduling",
        "Support day-to-day office administration"
      ],
      "qual": [
        "Excellent communication and presentation skills",
        "Customer-service experience",
        "Computer literacy and close attention to detail"
      ]
    },
    "ar": {
      "r": "موظف استقبال",
      "key": "موظف استقبال",
      "d": "الإدارة",
      "ty": "دوام كامل",
      "desc": "أن تكون الانطباع الأول الدافئ لطلاب ماسترز — استقبال العائلات وإدارة مكتب الاستقبال بسلاسة.",
      "resp": [
        "استقبال الزوار والرد على الاتصالات باحترافية",
        "التعامل مع استفسارات أولياء الأمور وجدولة المواعيد",
        "دعم المهام الإدارية المكتبية"
      ],
      "qual": [
        "مهارات تواصل ومظهر احترافي",
        "خبرة في خدمة العملاء",
        "إلمام بالحاسب والاهتمام الدقيق بالتفاصيل"
      ]
    }
  },
  {
    "id": "accountant",
    "order": 8,
    "en": {
      "r": "Accountant",
      "key": "Accountant",
      "d": "Finance",
      "ty": "Full-time",
      "desc": "Keep the school's finances accurate and transparent — from tuition records to monthly reporting.",
      "resp": [
        "Process fees, invoices and payments",
        "Maintain ledgers and reconcile accounts",
        "Prepare monthly financial reports"
      ],
      "qual": [
        "Degree in accounting or finance",
        "Experience with Egyptian accounting standards",
        "Strong Excel skills and high accuracy"
      ]
    },
    "ar": {
      "r": "محاسب",
      "key": "محاسب",
      "d": "الحسابات",
      "ty": "دوام كامل",
      "desc": "الحفاظ على دقة وشفافية مالية المدرسة — من سجلات الرسوم إلى التقارير الشهرية.",
      "resp": [
        "معالجة الرسوم والفواتير والمدفوعات",
        "إمساك الدفاتر وتسوية الحسابات",
        "إعداد التقارير المالية الشهرية"
      ],
      "qual": [
        "مؤهل في المحاسبة أو المالية",
        "خبرة في المعايير المحاسبية المصرية",
        "إتقان الإكسل والدقة العالية"
      ]
    }
  },
  {
    "id": "school-nurse",
    "order": 9,
    "en": {
      "r": "School Nurse",
      "key": "Nurse",
      "d": "Health",
      "ty": "Full-time",
      "desc": "Care for students' health and safety on campus, from first aid to health records.",
      "resp": [
        "Provide first aid and daily health care",
        "Maintain student health records",
        "Support health awareness programmes with staff"
      ],
      "qual": [
        "Nursing degree and a valid licence",
        "Paediatric or school-health experience",
        "Calm, caring and observant"
      ]
    },
    "ar": {
      "r": "ممرضة مدرسية",
      "key": "ممرضة",
      "d": "الصحة",
      "ty": "دوام كامل",
      "desc": "العناية بصحة وسلامة الطلاب في المدرسة — من الإسعافات الأولية إلى السجلات الصحية.",
      "resp": [
        "تقديم الإسعافات والرعاية الصحية اليومية",
        "صيانة السجلات الصحية للطلاب",
        "دعم برامج التوعية الصحية مع الموظفين"
      ],
      "qual": [
        "مؤهل تمريض ورخصة سارية",
        "خبرة في صحة الأطفال أو الصحة المدرسية",
        "هدوء ورعاية وملاحظة دقيقة"
      ]
    }
  },
  {
    "id": "administration-officer",
    "order": 10,
    "en": {
      "r": "Administration Officer",
      "key": "Administration",
      "d": "Administration",
      "ty": "Full-time",
      "desc": "Coordinate school operations and support the leadership team with organised, reliable administration.",
      "resp": [
        "Manage schedules, records and correspondence",
        "Coordinate with departments and parents",
        "Support events and daily operations"
      ],
      "qual": [
        "Degree in administration or equivalent",
        "Strong organisation and planning skills",
        "Proficiency in office software"
      ]
    },
    "ar": {
      "r": "موظف إداري",
      "key": "موظف إداري",
      "d": "الإدارة",
      "ty": "دوام كامل",
      "desc": "تنسيق عمليات المدرسة ودعم فريق القيادة بإدارة مكتبية منظمة وموثوقة.",
      "resp": [
        "إدارة الجداول والسجلات والمراسلات",
        "التنسيق بين الأقسام وأولياء الأمور",
        "دعم الفعاليات والعمليات اليومية"
      ],
      "qual": [
        "مؤهل في الإدارة أو ما يعادله",
        "مهارات تنظيم وتخطيط قوية",
        "إتقان برامج المكتب"
      ]
    }
  },
  {
    "id": "security",
    "order": 11,
    "en": {
      "r": "Security Personnel",
      "key": "Security",
      "d": "Security",
      "ty": "Full-time",
      "desc": "Protect students, staff and the campus, helping keep the school safe and welcoming.",
      "resp": [
        "Control site access and monitor the campus",
        "Respond quickly to any safety incident",
        "Support student arrival and dismissal routines"
      ],
      "qual": [
        "Previous security or military service is preferred",
        "Good judgement and professionalism",
        "Able to work school-day shifts"
      ]
    },
    "ar": {
      "r": "أفراد أمن",
      "key": "أمن",
      "d": "الأمن",
      "ty": "دوام كامل",
      "desc": "حماية الطلاب والموظفين ومرافق المدرسة والحفاظ على بيئة آمنة ومرحّبة.",
      "resp": [
        "التحكم في دخول الموقع ومراقبة المدرسة",
        "الاستجابة السريعة لأي حادث سلامة",
        "دعم إجراءات الحضور والانصراف"
      ],
      "qual": [
        "خبرة أمنية أو عسكرية سابقة ميزة",
        "حكمة جيدة واحترافية",
        "القدرة على العمل بنوبات اليوم الدراسي"
      ]
    }
  },
  {
    "id": "bus-driver",
    "order": 12,
    "en": {
      "r": "Bus Drivers",
      "key": "Bus Driver",
      "d": "Transport",
      "ty": "Full-time",
      "desc": "Transport students safely on fixed routes across El Santa and nearby areas, every school day.",
      "resp": [
        "Drive school buses on assigned routes safely",
        "Follow schedules and complete pre-trip safety checks",
        "Report vehicle issues promptly"
      ],
      "qual": [
        "Valid driver's licence and a clean record",
        "Experience driving large vehicles",
        "Patient, punctual and safety-focused"
      ]
    },
    "ar": {
      "r": "سائقو حافلات",
      "key": "سائق حافلة",
      "d": "النقل",
      "ty": "دوام كامل",
      "desc": "نقل الطلاب بأمان على مسارات ثابتة في السنطة والمناطق المجاورة طوال أيام الدراسة.",
      "resp": [
        "قيادة حافلات المدرسة على المسارات المحددة بأمان",
        "الالتزام بالجداول وإجراء الفحوصات قبل الانطلاق",
        "الإبلاغ الفوري عن أي أعطال في المركبة"
      ],
      "qual": [
        "رخصة قيادة سارية وسجل نظيف",
        "خبرة في قيادة المركبات الكبيرة",
        "صبر والالتزام بالمواعيد والسلامة"
      ]
    }
  },
  {
    "id": "bus-supervisor",
    "order": 13,
    "en": {
      "r": "Bus Supervisors",
      "key": "Bus Supervisor",
      "d": "Transport",
      "ty": "Full-time",
      "desc": "Look after students during bus journeys and coordinate smoothly with drivers and parents.",
      "resp": [
        "Supervise students on board at all times",
        "Maintain route rosters and attendance records",
        "Communicate updates to parents and the school"
      ],
      "qual": [
        "Experience caring for children in a similar role",
        "Responsible and alert",
        "Good communication skills"
      ]
    },
    "ar": {
      "r": "مشرفو حافلات",
      "key": "مشرف حافلة",
      "d": "النقل",
      "ty": "دوام كامل",
      "desc": "الاعتناء بالطلاب أثناء رحلات الحافلة والتنسيق بسلاسة مع السائقين وأولياء الأمور.",
      "resp": [
        "الإشراف على الطلاب طوال الرحلة",
        "صيانة جداول المسارات وسجلات الحضور",
        "إبلاغ أولياء الأمور والمدرسة بالتحديثات"
      ],
      "qual": [
        "خبرة في رعاية الأطفال في دور مشابه",
        "مسؤولية ويقظة دائمة",
        "مهارات تواصل جيدة"
      ]
    }
  }
];

var SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function slugify(title) {
  return String(title || 'job')
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'job';
}

module.exports = { SEED_JOBS: SEED_JOBS, SLUG_RE: SLUG_RE, slugify: slugify };
